# Generated by Django 5.0.7 on 2024-10-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_remove_workshop_teachers_delete_singleclass'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='student',
            name='primary_instrument',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='primary_instrument',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Normal',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
