# Generated by Django 5.1.2 on 2024-10-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('brass', 'Brass'), ('woodwind', 'Woodwind')], max_length=255)),
                ('image', models.ImageField(upload_to='instruments')),
                ('tone', models.CharField(choices=[('C', 'C'), ('Bb', 'Bb'), ('Eb', 'Eb')], max_length=255)),
            ],
        ),
    ]
