# Generated by Django 5.0.7 on 2024-10-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_instrument_image'),
        ('users', '0002_remove_student_instruments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
