# Generated by Django 5.0.7 on 2024-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reservation_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
