# Generated by Django 5.0.7 on 2024-10-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('vigente', 'vigente'), ('pasado', 'pasado'), ('proximo', 'proximo')], default='proximo', max_length=255),
        ),
    ]
