# Generated by Django 5.0.7 on 2024-10-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventReservation',
        ),
    ]
