# Generated by Django 5.0.7 on 2024-10-26 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleclass',
            name='student',
        ),
    ]
