# Generated by Django 5.0.7 on 2024-10-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_remove_singleclass_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='teachers',
        ),
        migrations.DeleteModel(
            name='SingleClass',
        ),
    ]
